git clone https://github.com/rhysd/clever-f.vim.git
git clone https://github.com/ctrlpvim/ctrlp.vim.git
git clone https://github.com/Raimondi/delimitMate.git
git clone https://github.com/morhetz/gruvbox.git
git clone https://github.com/nanotech/jellybeans.vim.git
git clone https://github.com/tomasr/molokai.git
git clone https://github.com/scrooloose/nerdcommenter.git
git clone https://github.com/motus/pig.vim.git
git clone https://github.com/unblevable/quick-scope.git
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/godlygeek/tabular.git
git clone https://github.com/majutsushi/tagbar
git clone https://github.com/ternjs/tern_for_vim.git
git clone https://github.com/coderifous/textobj-word-column.vim.git
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/vim-airline/vim-airline-themes
git clone https://github.com/gioele/vim-autoswap.git
git clone https://github.com/elixir-lang/vim-elixir.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/whatyouhide/vim-gotham.git
git clone https://github.com/ludovicchabant/vim-gutentags
git clone https://github.com/w0ng/vim-hybrid.git
git clone https://github.com/terryma/vim-multiple-cursors.git
git clone https://github.com/Shougo/vimproc.vim.git
git clone https://github.com/justinmk/vim-sneak.git
git clone https://github.com/tpope/vim-surround.git
