#! /bin/sh

# set keyboard layout
setxkbmap -layout cz -variant qwerty_bksl

# setxkbmap turns off numlock LED for some reason - turn numlock off and on to fix
numlockx off; numlockx on;

xset b off

# set screen timeout
xset s 3600 3600 -dpms

light-locker &
mpd &
sh ~/.fehbg &
compton --conf ~/.config/compton.conf &
export _JAVA_AWT_WM_NONREPARENTING=1 &
wmname LG3D &
dunst &

autocutsel -fork &
autocutsel -selection PRIMARY -fork &

sxhkd &

bspc config border_width         2
bspc config active_border_color  "#7FD4F0"
bspc config focused_border_color "#7FD4F0"
bspc config window_gap          10
bspc config top_padding         16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI

bspc rule -a Gimp state=floating follow=on
bspc rule -a Xdialog state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a steam floating=on

#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

panel &
