#! /bin/sh
bspc config border_width         1
bspc config normal_border_color  "#10151B"
bspc config active_border_color  "#7FD4F0"
bspc config focused_border_color "#7FD4F0"
bspc config window_gap          1
bspc config top_padding         16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus       true

bspc monitor -d 1 2 3 4 5 6 7 8

bspc rule -a Gimp state=floating follow=on
bspc rule -a Xdialog state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a steam floating=on

panel &
