#! /bin/sh
#
# Example panel for lemonbar

. panel_colors

num_mon=$(bspc query -M | wc -l)

 #initialization
pac=" \ue1bc - "
trash="  - "
volume="%{F$COLOR_VOLUME}%{B$COLOR_SYS_BG} \ue204 - %{B-}%{F-}"
track="%{F$COLOR_MUSIC_PAUSED}%{B$COLOR_SYS_BG}Loading track... %{B-}%{F-}"

while read -r line ; do
	case $line in
        B*)
            # battery percent output

            BAT_COLOR=$COLOR_BATTERY_HIGH
            batNum=$(echo "$line" | egrep -o "([0-9]+)" | cut -d' ' -f2)

            if [ "$batNum" -ge "0" ] && [ "$batNum" -le "10" ];
            then
                BAT_COLOR=$COLOR_BATTERY_DEAD
            elif [ "$batNum" -gt "10" ] && [ "$batNum" -le "50" ];
            then
                BAT_COLOR=$COLOR_BATTERY_LOW
            elif [ "$batNum" -gt "50" ] && [ "$batNum" -le "75" ];
            then
                BAT_COLOR=$COLOR_BATTERY_MID
            fi
            battery="%{F$BAT_COLOR}%{B$COLOR_SYS_BG} ${line#?}%{B-}%{F-}"
            ;;
        E*)
            # estimated time left on battery/to charge until full

            symbol=" »"
            padding=" "
            est_time_color=$COLOR_URGENT_FG
            case "$line" in
                *'') # Charging
                    est_time_color=$COLOR_FOCUSED_OCCUPIED_FG
                    ;;
                *'') # Discharging
                    est_time_color=$COLOR_OCCUPIED_FG
                    ;;
                *)
                    symbol=""
                    padding=""
                    ;;
            esac
            est_time="%{B$COLOR_SYS_BG}$symbol%{F$est_time_color}$padding${line#?} %{B-}%{F-}"
            ;;
        R*)
            # trash

            trash=${line#?}
            trash_color=$COLOR_FOCUSED_OCCUPIED_FG
            trashnum=$(echo "$trash" | cut -d' ' -f3)
            if [ "$trashnum" -lt 1 ]
            then
                trash_color=$COLOR_OCCUPIED_FG
                trash=$(echo "$trash" | sed "s/$trashnum/%{F$COLOR_FOCUSED_OCCUPIED_FG}$trashnum%{F-}/")
            fi
            trash="%{F$trash_color}%{B$COLOR_SYS_BG}$trash%{B-}%{F-}"
            ;;
        P*)
            # pacman upgrades

            pac=${line#?}
            pac_color=$COLOR_FOCUSED_OCCUPIED_FG
            case "$pac" in
                *''*) #empty star
                    pac=$(echo -e "$pac" | sed "s/\ue1bc/%{F$COLOR_OCCUPIED_FG}\ue1bc%{F$pac_color}/")
                    ;;
                *''*) #full star
                    pac=$(echo -e "$pac" | sed "s/\ue1c2/%{F$COLOR_URGENT_FG}\ue1c2%{F$pac_color}/")
                    ;;
            esac
            pac="%{F$pac_color}%{B$COLOR_SYS_BG}$pac%{B-}%{F-}"
            ;;
        V*)
            # volume

            volume=" ${line#?} "
            # mouse controls
            volume="%{A4:sh update_volume.sh up:}$volume%{A}"
            volume="%{A5:sh update_volume.sh down:}$volume%{A}"
            volume="%{A:sh volume.sh & disown:}$volume%{A}"

            volume="%{F$COLOR_VOLUME}%{B$COLOR_SYS_BG}$volume%{B-}%{F-}"
            ;;
        M*)
            # current track
            line=${line#?}
            spotify=0
            music_color=$COLOR_MUSIC_PLAYING
            track_color=$COLOR_MUSIC_PLAYING_TRACK
            under_color=$COLOR_MUSIC_PLAYING
            case "$line" in
                *"MPD off")
                    music_color=$COLOR_MPD_OFF
                    ;;
                *''*) # paused
                    music_color=$COLOR_MUSIC_PAUSED
                    track_color=$COLOR_MUSIC_PAUSED_TRACK
                    under_color=$COLOR_MUSIC_PAUSED
                    ;;
                *''*) # spotify
                    line=${line#?}
                    spotify=1
                    music_color=$COLOR_SPOTIFY
                    track_color=$COLOR_SPOTIFY_TRACK
                    under_color=$COLOR_SPOTIFY
                    case "$line" in
                        A*)
                            music_color=$COLOR_SPOTIFY
                            track_color=$COLOR_SPOTIFY_TRACK
                            under_color=$COLOR_SPOTIFY
                            ;;
                        S*)
                            music_color=$COLOR_SPOTIFY_PAUSED
                            track_color=$COLOR_SPOTIFY_PAUSED_TRACK
                            under_color=$COLOR_SPOTIFY_PAUSED
                            ;;
                    esac
                    line=${line#?}
                    ;;
            esac
            # underline/highlight track name
            track=$(echo "$line" | sed "s/\ -\ \(.*\)$/\ -\ %{F$track_color}%{U$under_color}%{+u}\1%{-u}%{U-}%{F$music_color}/")
            track="%{F$music_color}%{B$COLOR_SYS_BG}${track} %{B-}%{F-}"
            if [ "$spotify" = 1 ]
            then
                # LMB to toggle play/pause
                track="%{A:dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause;~/.config/bspwm/paneldir/spotify_current_track.sh:}$track%{A}"
                # RMB to go to next song
                track="%{A3:dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next;~/.config/bspwm/paneldir/spotify_current_track.sh:}$track%{A}"
            else
                # mouse controls
                # LMB to toggle play/pause
                track="%{A:mpc toggle:}$track%{A}"
                # Middle click to start/quit ncmpcpp
                track="%{A2:sh toggle_ncm.sh & disown:}$track%{A}"
                # RMB to go to next song
                track="%{A3:mpc next:}$track%{A}"
                # Mousewheel to adjust volume
                track="%{A4:mpc volume +5:}$track%{A}"
                track="%{A5:mpc volume -5:}$track%{A}"
            fi
            ;;
        L*)
            # wifi

            WIFI_COLOR=$COLOR_WIFI_CONNECTING
            line=${line#?}
            case "$line" in
                A*)
                    WIFI_COLOR=$COLOR_WIFI_CONNECTED
                    ;;
                D*)
                    WIFI_COLOR=$COLOR_WIFI_DISCONNECTED
                    ;;
            esac
            wifi="%{F$WIFI_COLOR}%{B$COLOR_SYS_BG}%{A:sh toggle_wpa_gui.sh & disown:}${line#?} %{A}%{B-}%{F-}"
            ;;
        D*)
            # date output

            date="%{F$COLOR_DATE}%{B$COLOR_SYS_BG}${line#?} %{B-}%{F-}"
            ;;
		S*)
			# clock output

			sys="%{F$COLOR_TIME}%{B$COLOR_SYS_BG} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output

            title="%{F$COLOR_TITLE_FG}%{B$COLOR_SYS_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state

			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ "$num_mon" -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							F*)
								# focused free desktop
								FG=$COLOR_FREE_FG
                                BG=$COLOR_FOCUSED_BG
                                UG=$COLOR_UNDERLINE
                                wm="${wm}%{B${BG}}%{F${FG}}%{U${UG}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{-u}%{U-}%{F-}%{B-}"
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
                                BG=$COLOR_FOCUSED_BG
                                UG=$COLOR_UNDERLINE
                                wm="${wm}%{B${BG}}%{F${FG}}%{U${UG}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{-u}%{U-}%{F-}%{B-}"
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_URGENT_FG
                                BG=$COLOR_FOCUSED_BG
                                UG=$COLOR_UNDERLINE
                                wm="${wm}%{B${BG}}%{F${FG}}%{U${UG}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{-u}%{U-}%{F-}%{B-}"
								;;
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
                                wm="${wm}%{F${FG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{F-}"
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
                                wm="${wm}%{F${FG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{F-}"
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
                                wm="${wm}%{F${FG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{F-}"
								;;
						esac
						;;
				esac
				shift
			done
			;;
	esac
    power="%{F$COLOR_POWER}%{B${COLOR_SYS_BG}}%{A:sh shutdowndialog.sh & disown:} \ue00d %{A}%{B-}%{F-}"
	echo -e "%{l}${wm}${title}%{r}  ${track}|${battery}${est_time}|${wifi}|${volume}|${pac}|${trash}|${date}|${sys}|${power}"

done
