#! /bin/sh
#
# Example panel for lemonbar

. panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
        B*)
            # battery percent output
            BAT_COLOR=$COLOR_BATTERY_HIGH
            batNum=$(echo $line | egrep -o "([0-9]+)" | cut -d' ' -f2)

            if [ "$batNum" -ge "0" ] && [ "$batNum" -le "10" ];
            then
                BAT_COLOR=$COLOR_BATTERY_DEAD
            elif [ "$batNum" -gt "10" ] && [ "$batNum" -le "50" ];
            then
                BAT_COLOR=$COLOR_BATTERY_LOW
            elif [ "$batNum" -gt "50" ] && [ "$batNum" -le "75" ];
            then
                BAT_COLOR=$COLOR_BATTERY_MID
            fi
            battery="%{F$BAT_COLOR}%{B$COLOR_SYS_BG}$PADDING${line#?}%{B-}%{F-}"
            ;;
        E*)
            if [[ $line == *'+' ]] #charging
            then
                est_time_color=$COLOR_TITLE_FG
            elif [[ $line == *'-' ]] #discharging
            then
                est_time_color=$BAT_COLOR
            fi
            est_time="%{F$est_time_color}%{B$COLOR_SYS_BG}${line#?} %{B-}%{F-}"
            ;;
        V*)
            # alsa volume
            volume="%{F$COLOR_VOLUME}%{B$COLOR_SYS_BG}%{A:sh volume.sh & disown:}$PADDING${line#?} %{A}%{B-}%{F-}"
            ;;
        M*)
            # current track
            music_color=$COLOR_MUSIC_PLAYING
            track_color=$COLOR_MUSIC_PLAYING_TRACK
            if [[ $line == *"MPD off" ]]
            then
                music_color=$COLOR_WIFI_DISCONNECTED
            elif [[ $line == *''* ]] #paused
            then
                music_color=$COLOR_MUSIC_PAUSED
                track_color=$COLOR_MUSIC_PAUSED_TRACK
            elif [[ $line == *''* ]] #spotify
            then
                music_color=$COLOR_SPOTIFY
                track_color=$COLOR_SPOTIFY_TRACK
            fi
            under_color=$COLOR_UNDERLINE
            #underline track name
            track=$(echo "$line" | sed "s/\ -\ \(.*\)\(..\)$/\ -\ %{F$track_color}%{U$under_color}%{+u}\1%{-u}%{U-}%{F$music_color}\2/")
            track="%{F$music_color}%{B$COLOR_SYS_BG}$PADDING${track#?} %{B-}%{F-}"
            ;;
        L*)
            # wifi link
            WIFI_COLOR=$COLOR_WIFI_CONNECTING
            if [[ $line == *""* ]]
            then
                WIFI_COLOR=$COLOR_WIFI_CONNECTED
            elif [[ $line == *""* ]]
            then
                WIFI_COLOR=$COLOR_WIFI_DISCONNECTED
            fi
            wifi="%{F$WIFI_COLOR}%{B$COLOR_SYS_BG}%{A:sh toggle_wpa_gui.sh & disown:}$PADDING${line#?} %{A}%{B-}%{F-}"
            ;;
        D*)
            # date output
            date="%{F$COLOR_DATE}%{B$COLOR_SYS_BG}$PADDING${line#?} %{B-}%{F-}"
            ;;
		S*)
			# clock output
			sys="%{F$COLOR_TIME}%{B$COLOR_SYS_BG} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
            title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							F*)
								# focused free desktop
								FG=$COLOR_FREE_FG
                                UG=$COLOR_UNDERLINE
                                wm="${wm}%{F${FG}}%{U$COLOR_UNDERLINE}%{+u}$PADDING%{A:bspc desktop -f ${name}:} ${name} %{A}%{-u}%{U-}%{F-}"
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
                                UG=$COLOR_UNDERLINE
                                wm="${wm}%{F${FG}}%{U$COLOR_UNDERLINE}%{+u}$PADDING%{A:bspc desktop -f ${name}:} ${name} %{A}%{-u}%{U-}%{F-}"
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_URGENT_FG
                                UG=$COLOR_UNDERLINE
                                wm="${wm}%{F${FG}}%{U$COLOR_UNDERLINE}%{+u}$PADDING%{A:bspc desktop -f ${name}:} ${name} %{A}%{-u}%{U-}%{F-}"
								;;
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
                                wm="${wm}%{F${FG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{F-}"
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
                                wm="${wm}%{F${FG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{F-}"
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
                                wm="${wm}%{F${FG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{F-}"
								;;
						esac
						;;
					#[fFoOuU]*)
						#case $item in
							#f*)
								## free desktop
								#FG=$COLOR_FREE_FG
								#BG=$COLOR_FREE_BG
								#;;
							#F*)
								## focused free desktop
								#FG=$COLOR_FOCUSED_FREE_FG
								#BG=$COLOR_FOCUSED_FREE_BG
								#;;
							#o*)
								## occupied desktop
								#FG=$COLOR_OCCUPIED_FG
								#BG=$COLOR_OCCUPIED_BG
								#;;
							#O*)
								## focused occupied desktop
								#FG=$COLOR_FOCUSED_OCCUPIED_FG
								#BG=$COLOR_FOCUSED_OCCUPIED_BG
								#;;
							#u*)
								## urgent desktop
								#FG=$COLOR_URGENT_FG
								#BG=$COLOR_URGENT_BG
								#;;
							#U*)
								## focused urgent desktop
								#FG=$COLOR_FOCUSED_URGENT_FG
								#BG=$COLOR_FOCUSED_URGENT_BG
								#;;
						#esac
						#wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						#;;
					#[LTG]*)
						## layout, state and flags
						#wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
						#;;
				esac
				shift
			done
			;;
	esac
    power=" %{F$COLOR_POWER_BUTTON}%{B${BG}}%{A:sh shutdowndialog.sh & disown:} %{A}%{B-}%{F-} "
	printf "%s\n" "%{l}${wm}${title}%{r}  ${track}| ${battery}${est_time}|${wifi}| ${volume}|${date}|${sys}|${power}"

done
